---
- name: Copy GitLab configuration file.
  template:
    src: gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
    owner: root
    group: root
    mode: 'u=rw,g=r,o=r'
    backup: yes
  notify: restart gitlab
